### ISSUE TITLE
Update file deletion messaging

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#1000]
#931 is implementing a new modal for warning messages.

This issue should investigate the different messages presented when files are deleted, covering the many use cases, and update the warning messages so that the outcome is clear to the user.

Tasks:
- Outline the different use cases for displaying messages, i.e all files are in use; 'x' number of the selected files are in use; perhaps telling the users where those files are being used.
- Create the messages required for each use case.

Notes:
- #931 opens up the opportunity for what information can be used in the modal about the files. Look into what's best to use.
- The model should be utilising the new reactstrap-confirm component.

**PRs**

- [ ] #1043

**Comment by newleeland** [comment]
### Potential Recommendation
Replace browser alert, with a real bootstrap modal:
Title: This file is currently in use in 6 places, are you sure you want to delete it?
Body:Ensure files are removed from content areas prior to deleting them, otherwise they will appear as broken links.
Primary Button: Keep files 
Secondary buttons: delete anyway

**Comment by brynwhyman** [comment]
We should have a look at the endpoints built with #931 to see if it makes sense to be utilised here.

**Comment by bergice** [comment]
We can just use https://www.npmjs.com/package/@silverstripe/reactstrap-confirm for this.

**Comment by sachajudd** [comment]
Previously we were under the impression that we couldn’t get a list of files being used in the modal but after chatting with @maxime-rainville it seems like it’s possible. Given this information and some user testing, there are a few scenarios that we haven’t covered (given the old behaviour being replicated). I feel like we can reduce some of the file deletion messages and make it easier for the user to understand how many files are in use and places which they are used on.

At the moment there are 4 different scenarios with multiple file deletion messages:
- You’re trying to delete a folder containing a file in use 
- There’s nothing in use in what you’ve selected
- You’re trying to delete 1 file and it’s in use
- You’re trying to delete more than one file and some of them are in use

We think we can reduce the file deletion messages to 2 for these scenarios and include the following uncatered scenarios:
- You’re trying to delete files and folders in use (previously would dismiss the user which was a disjointed experience to other file deletion options).
- Folder contains another folder that contains a file in use (see #).

**File deletion message 1**
**Catering to the following scenarios:**
a) Deleting an individual file in use
b) Deleting a folder with files in use
c) Deleting files, and folders with files in use
**Modal title:** Confirm file deletion
**Message:** x files are currently in use in x place(s), are you sure you want to delete them?
Ensure files are removed from content areas prior to deleting them, otherwise they will appear as broken links.
**List of files:** (See # for more details)
**Buttons:** Cancel (btn-primary) / Delete (btn-danger)

Max raised a good point around how many files we say are currently in use:
> Let's say you select 2 files: 5 pages are using file A, 5 pages are using file B and 5 pages are using File A and B. Should I say that file A and B are used in 20 places or 15 places?

After some discussion we think we should let the user know of all the places the file is currently being used. So in this case it would be 20.

**File deletion message 2**
**Catering to the following scenarios:**
a) Deleting folders/files with no files in use
**Modal title:** Confirm file deletion
**Message:** Are you sure you want to delete these files/folders?
**List of files:** (See # for more details)
**Buttons:** Delete (btn-danger) / Cancel (btn-secondary)

For this ticket I think we should just focus on adding the deletion messages for the scenarios and buttons. I’ll make a separate issue for the “List of files” as I think this is out of scope for this ticket. Let us know if you have any thoughts!

**Comment by brynwhyman** [comment]
Nice to see the different messages being consolidated! Thanks @sachajudd

**Comment by brynwhyman** [comment]
Perhaps this was more of a question for new endpoint created in #931, but what is the usage count of a file including as a 'count'? Is it just counting at a page level or at a deeper level e.g. data object, elemental area, etc. 

We found different handling was unnecessarily duplicating the count in https://github.com/silverstripe/silverstripe-asset-admin/issues/903

**Comment by Cheddam** [comment]
I've reviewed the messaging currently in place vs. the messaging recommended by @sachajudd, and had a chat to her. We're going to go forward with the proposed messages, but also use singular and plural variants (bringing the total to 4 messages) to make them more readable in cases where the user is only deleting a single item.

**Comment by Cheddam** [comment]
I've raised a PR at #1043. Due to limitations in the data we receive from the GraphQL query, I've revised the message list to the following:

- Multiple 'items' in use (when the selection contains a mix of files and folders in use, or a mix of used and not-used files/folders)
- Single file / multiple files in use
- Single folder / multiple folders in use
- Single item / multiple 'items' _not_ in use
