### ISSUE TITLE
Navigating in breadcrumb redirects to admin/assets

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-asset-admin#1007]
## Overview
When navigating the file gallery to upload a file through the upload field, if you navigate to any file folders in the breadcrumb, you're redirected away from the page you're editing to a broken assets page with no path to return to the page you were editing.

## Version affected
silverstripe/asset-admin  1.4.2
silverstripe/framework 4.4.3 

## To reproduce
1. Select 'Add from files' in an uploadfield (I used the one available in a File block)
2. Attempt to navigate to another folder by selecting one in the breadcrumb 

**Expected result**
- You are taken to the selected folder, can select a file, and insert it.

**Actual result** 
- You are redirected away from editing a page to /admin/assets with an empty page (no file gallery showing)

## Acceptance criteria
- [x] When interacting with the breadcrumb in the InsertMedia modal and UploadField modal, the location of the modal is updated without taking the user to the asset-admin area
- [x] If you you cancel the modal without updating the file reference, nothing is changed in the UploadField/WYSIWYG
- [ ] The breadcrumb interaction is covered by Behat test
- [x] The Back button next to the breadcrumb also works as expected.

## Pull requests
- silverstripe/silverstripe-admin#1299
- #1265
- silverstripe/silverstripe-elemental-fileblock#29

**Comment by maxime-rainville** [comment]
@silverstripeux A good candidate for the Exp debt epic.

Here's what happens. https://youtu.be/QN87a86dwSE

**Comment by GuySartorelli** [comment]
Interestingly, this _doesn't_ happen for an `UploadField` on a page directly. It _does_ happen for an `UploadField` in an elemental block, whether that block is inline editable or not.

**Comment by GuySartorelli** [comment]
Whatever's causing the problem isn't any of the javascript packaged with the elemental module. I have tried stopping all of that javascript from being included, and the problem is still occurring. Yet applying `ElementalPageExtension` is reliably the way to introduce the problem.
I'm a bit stumped.

**Comment by GuySartorelli** [comment]
Debugging the javascript to see what happens in `AssetAdminBreadcrumb`'s click handler, I can see that by the time that breakpoint is hit the URL in the browser's address bar has already been set to the asset admin section.

Without applying the extension, I can see when the page router's click handler is triggered, the event's `defaultPrevented` property is set to `true`, which is what we would expect. But when the `ElementalPageExtension` is applied to the page, `defaultPrevented` is `false`.

In both cases the breakpoint for the click handler gets hit before the breadcrumb click event called `preventDefault()`, which suggests that there must be some other conditional call to `preventDefault()` elsewhere which, when the extension isn't applied, gets triggered prior to the page router's click handler. Gonna dig in even deeper to see if I can find it.

**Comment by GuySartorelli** [comment]
It's a bit hard to explain what I'm seeing, so I've recorded what happens _without_ the extension, and what happens _with_ the extension, including breakpoints. The first breakpoint that's triggered is in the page router's `onClick` function. The second is the `onClick` function inside the `AssetAdminBreadcrumb' component.

Without `ElementalPageExtension`:

https://user-images.githubusercontent.com/36352093/161486694-c78db2d2-6087-47bd-90e8-f843bca87895.mp4

With `ElementalPageExtension`:

https://user-images.githubusercontent.com/36352093/161486743-372cc133-ea69-4db2-b8c2-a5af8de1cf54.mp4

I'm not sure if the order in which these are being triggered is a red herring (i.e. is the call to `preventDefault()` actually happening before the page router gets triggered but the browser is choosing to show me something different?) or if there is in fact some other event handler at play before the router, which for some reason doesn't get triggered (or at least doesn't prevent the default action on the click event) when that extension is applied to the page.
In any case I'm really not sure where to look next.

**Comment by GuySartorelli** [comment]
So it turns out that the reason it works as expected before `ElementalPageExtension` is applied to the page is because without that extension, the normal `Content` field is present - and the tinymce javascript includes an entwine click handler for the insert image modal which happens to match the selector for the breadcrumb link used in the `UploadField`'s modal.

The problem ultimately is that entwine and plain js click handlers are all handled before react click handlers.
The order of operations when the tinymce javascript is present is this:
1. The tinymce click handler for the breadcrumb link selector gets called and calls `preventDefault()` on the event
2. The page router's global click handler gets called. It recognises that the event's default is prevented and doesn't do anything.
3. Finally the react click handler is called, and does the correct update to the modal.

When the tinymce javascript is _not_ present (because the `Content` WYSIWYG field is replaced with an elemental area), the event's default action is _not_ prevented prior to the page router's handler being called, so it sees that a link was clicked and tries to navigate to the assets section of the CMS.

Not sure what a good solution would be yet. The hacky solution would just be to slap a new entwine click handler targetting the breadcrumb link that just calls `preventDefault`, but if there's a way to fix the race condition instead and let react click handlers be processed before the page router then that would obviously be better, as it would address any potential instances of this elsewhere.
Another option would be to turn the link into a symantic button, I guess. The page router ignores buttons. But then middle mouse clicking for example would be broken for them since they're not links anymore.

**Comment by emteknetnz** [comment]
If you need to do the 'hack' solution, https://github.com/silverstripe/silverstripe-elemental/blob/4/client/src/legacy/ElementEditor/entwine.js may be a good location to put it in, as it's entwine code used to load the elemental react component

**Comment by GuySartorelli** [comment]
I think the problem is less adding elemental specifically, and more removing the `Content` field, which could potentially be done for other reasons as well. It would need to be code that is added for any situation where the `UploadField` could potentially be present, regardless of what other modules may be present.

**Comment by emteknetnz** [comment]
Seems like what you're wanting to do then is decouple some of the 'extra' code around the `Content` field.

Could you link to the `Content` field code that adds `preventDefault()`?

**Comment by GuySartorelli** [comment]
I guess it's not even the `Content` field specifically so much as any HtmlEditorField that uses tinymce - the relevant code is in the `assets/_tinymce/tinymce-cms-2d1079444d.js` file which was generated by `SilverStripe\Forms\HTMLEditor\TinyMCECombinedGenerator`. I'm still in the process of tracing _exactly_ where the relevant bit of code comes from, but it looks like this:

```js
_jquery2.default.entwine('ss', function ($) {
  $('.insert-media-react__dialog-wrapper .nav-link, ' + '.insert-media-react__dialog-wrapper .breadcrumb__container a').entwine({
    onclick: function onclick(e) {
      return e.preventDefault();
    }
  });
  //... etc more code here
});
```

**Comment by emteknetnz** [comment]
Source is here https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/entwine/TinyMCE_ssmedia.js#L149
