### ISSUE TITLE
TinyMCE / sanitiseShortCodeProperties is not a function

### ISSUE THREAD

**Issue by thats4shaw** [silverstripe/silverstripe-asset-admin#1012]
When inserting an image through TinyMCE you are now greeted with the following error:

```TypeError: (0 , g.sanitiseShortCodeProperties) is not a function```

Affects SilverStripe 4.4.4.  

I also believe this is a problem in https://github.com/silverstripe/silverstripe-admin/ as same error appears when saving a page with a `HTMLEditorField` with images.

**Comment by dnsl48** [comment]
Accidentally incorrect versions of `silverstripe/admin` were tagged as 1.4.4 and 1.3.5.
This has been caused by issues with our release tooling.

We have fixed the tags as soon as we've been notified by our CI tooling. Unfortunately, the incorrect tags have been published for some time (overnight).

You seem to be among those who have been lucky enough to pull the incorrect update.
To resolve the issue the correct version of the `silverstripe/admin` module should be installed, which are:
 - 1.4.4 : a3eaf95bb2e37641d5a2f476807cc9696d55fac4
 - 1.3.5 : 6e6fa5c618b9dbf4cc0a56704834bfa1d5b0d18e

I'm not exactly sure if simple `composer update` would fix that, but I have a feeling it should.

**Comment by xyphoid** [comment]
Cheers - composer update after trashing the vendor folder gets correct versions of this.

**Comment by maxime-rainville** [comment]
So is there anything else to do to address this?

**Comment by thats4shaw** [comment]
Sorted from my perspective - thanks for the quick turnaround!

**Comment by dnsl48** [comment]
I've modified the issue title so others should be able to find this issue easily.
The solution is `composer update`
