### ISSUE TITLE
Unversioned DataObject HTMLTextField inserted images don't get published on save

### ISSUE THREAD

**Issue by IsaacInsoll** [silverstripe/silverstripe-asset-admin#1032]
We have some non-versioned DataObjects in our CMS that have HTMLText fields. 
When users upload an image to the field and save it they can't see any images that they have inserted because those images aren't getting published when the DataObject is saved. 

From the front end it just appears that the images are missing. If I manually go in and publish the image via asset admin then it appears on the front end as expected. 

Desired behaviour: publish any images in HTMLText fields when DataObject is written as otherwise it's a very weird experience for the user who assumes images are disappearing.

**Comment by maxime-rainville** [comment]
Thanks for taking the time to report this issue.

I'm just clarifying my understanding of what you are describing:
* You have some unversioned  `DataObject` with a `Content` field of the `HTMLText` type.
* The CMS user edit this DataObject via a ModelAdmin and adds an Image to the Content field.
* The CMS user saves the DataObject.
* The Content of the DataObjects gets displayed in the web site front end.

**What you expect**: The image included in the Content of the DataObject should have been automatically published and should be visible on the front end.

**Actual behaviour**: The image has not been published and appear has a broken image on the front end.

If my understanding of the issue is correct, I think this is actually the intended behaviour. If we alter the behaviour as you describe, we'll probably cause a lot of issues for developers that don't expect related records to be auto-publish on save.

In this case, I think it's better to let developers who need this behaviour implement it themselves. One way you could achieve your desired behaviour is to use the `onAfterWrite()` hook on your DataObject to call the `publishRecursive()` method. `publishRecursive()` is available on DataObject even if they are not versioned. It will read any HTMLText field and publish any referenced images/files in it.
