### ISSUE TITLE
Insert/Update image button text

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#1086]
Minor UX issue that came about after merging the inline editing PR
https://github.com/silverstripe/silverstripe-asset-admin/pull/1038

When I edit a page
And I use TinyMCE
And I click the insert an image button
And I upload a new image
And I click the "Details" button in the top right corner
And I change the "Title" of the image
And I click the "Save" button
Then I expect to see the green button to have the text "Insert image"
But actually it has the text "Update image"

I believe it also affects 'Insert/Update file' when dealing with a PDF

We decided to leave this issue in place and merged anyway as it wasn't deemed as overly-important https://github.com/silverstripe/silverstripe-asset-admin/pull/1038#issuecomment-623192832

### PR
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1115

### Notes
* We've found that there's an issue with state management. The button text is being determined client-side so may be subject to having the state potentially cached and not always showing the correct button text for the context.
* When looking at this, we'll want to tidy up another area that @maxime-rainville has suggested (please add context here :) )

**Comment by maxime-rainville** [comment]
The underlying problem is caused by this bit: https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/transforms/AssetAdmin/insertAssetModal.js

This logic gets run when fetch the FileInsertMedia form schema. It checks if there's any form value override for that form schema. When you're inserting a new image there's no overrides to provide, so we use the "insert" label. When you're updating an existing image, the short code info in the WYSIWYG gets pushed to the modal as a form value overrides.

The problem is that when you edit the original file, you're placement info gets recalled with form value overrides. Here's what happens in the background:
* User clicks the "insert image" button. No form value overrides are pushed to the modal.
* Modal gets displayed.
* User selects an image. We fetch the form schema. No override are apply.
  * The `insertAssetModal` transformation is applied. Because there's no overrides, we set the button label to "Insert".
* User decides to edit the original info of the image. Current placement info is stash to the redux store.
* User returns to insert media form.
  * We restore the placement info to the form with form value overrides
  * We refetch the insert media schema.
  * The `insertAssetModal` transformation is applied. Because there IS overrides this time, we set the button label to "Update".

**Comment by maxime-rainville** [comment]
FYI ... I tried fixing this passing an extra bit of info in the redux store to specify if we're adding a new image or inserting a new one. However, the `insertAssetModal` can't access the current state. Even if you try to use the Injector to get a reference to `getState`, when you call you get an error that says that you can't access the state while you're in the process of updating it.

I'm thinking the best fix woul be to pass an extra parameter to the formSchema request that specify the pre-exisintg image ID so we can decide which label to display server side.

**Comment by clarkepaul** [comment]
> When you're inserting a new image there's no overrides to provide, so we use the "insert" label. 

@maxime-rainville I've just tested placing an existing file without doing any edits or changes and the button says "Update file" rather than "Insert". I don't see time at all now where it says "Insert".

Steps:
1. In TinyMCE click the file bottom, file admin appears in modal
2. Select a file you want to insert
3. In the file edit panel, the button at the bottom read "Update file" (should read "Insert file")

**Comment by brynwhyman** [comment]
Added more info to the description under the notes, @maxime-rainville can provide more context though

**Comment by maxime-rainville** [comment]
Fixed.
