### ISSUE TITLE
Responsive image alignment

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-asset-admin#1096]
# Responsive image alignment

This is one of the features that we keep re-implementing in almost every single project which allows images inside HTML fields. Out of the box HTML editor forces fixed dimensions on an image which is actually undesirable as most of the images need to be responsive.

I suggest to add out of the box support for Responsive (Fluid) image alignment with recommendation added to the documentation on how to integrate such styles into a project.

I'm providing working code snippets and some images to showcase the solution.

## CMS UI

Image below shows the new Fluid (responsive) option for image alignment. Note that this is a new option so it doesn't change any existing functionality. I'm using existing icon in my example, but we probably need a new icon for the fluid option.

![Screen Shot 2020-06-03 at 11 43 05 AM](https://user-images.githubusercontent.com/26395487/83580220-92cc7280-a58f-11ea-945e-eec4f8483009.png)

## HTML class

I decided to go with `centerAlone` as this name seems to be unused.

## Suggested styles (both CMS and frontend)

```
img.centerAlone {
  height: auto;
  width: 100%;
}

```

Sample code to add the option:

```
<?php

namespace App\HtmlEditor;

use SilverStripe\AssetAdmin\Forms\ImageFormFactory;
use SilverStripe\Core\Extension as BaseExtension;
use SilverStripe\Forms\Form;
use SilverStripe\Forms\OptionsetField;

/**
 * Class Extension
 *
 * Customise image alignment options for the HTML field UI
 *
 * @property ImageFormFactory $owner
 * @package App\HtmlEditor
 */
class Extension extends BaseExtension
{
    /**
     * Extension point in @see ImageFormFactory::getForm()
     *
     * @param Form $form
     * @param $controller
     * @param $name
     * @param $context
     */
    public function updateForm(// phpcs:ignore SlevomatCodingStandard.TypeHints
        Form $form,
        $controller,
        $name,
        $context
    ): void {
        $fields = $form->Fields();

        /** @var OptionsetField $alignment */
        $alignment = $fields->fieldByName('Editor.Placement.Alignment');

        if (!$alignment) {
            return;
        }

        $source = $alignment->getSource();
        $source['centerAlone'] = 'Fluid';

        $alignment->setSource($source);
    }
}
```

Feedback appreciated ;-)

**Comment by maxime-rainville** [comment]
I'm not sure we want to support it out of the box, but we could add an API that makes it trivial to add additional placement option.

@silverstripeux Got views on this?

**Comment by clarkepaul** [comment]
I've built lots of sites using the existing file UI and had files act responsively, I just add max-width 100% on all the files in content areas so that it only uses a maximum 100% of the width available. This means the file still uses the preferred positioning but the file will never grow bigger than it has been uploaded or set at.

@mfendeksilverstripe with your suggestion, you'd want to remove the dimensions fields as your just overriding them? but you will also run into the issue of enlarged images bigger than they are supposed to be displayed at (pixelated) I think.

My recommendation to change the default width (600px) of images to the maximum width of the available space on the page (or larger than it). Then you will never be scaling images up, also try just adding max-width 100% to images to get the desired result of responsiveness. Don't forget to add max-width 100% on the caption wrapper etc too otherwise images tend to extend out of view.

Hopefully I understood the intended customisation?

**Comment by mfendeksilverstripe** [comment]
Thanks for clarification @clarkepaul . I'm aware that such customisations are possible but I think the main question is if we should have the Responsive option available out of the box. I can't think of a project which would not want to have responsive images as an option in the WYSIWYG UI. Is there are reason why we don't want to have this option out of the box?

Note that I'm suggesting making changes to the WYSIWYG UI not the frontend (as that would be left on the bespoke code).

**Comment by clarkepaul** [comment]
> I can't think of a project which would not want to have responsive images

Agree, that's why as a developer I would always put max-width 100% on images, so that means for my cms users that option wouldn't need to be applied, and that its the default (it's only a few lines of CSS).

I always thought it should be the designers/developers who should make that decision site-wide rather than based on individual cases. Hence that's why I would rather build it into the template to be responsive by default (scaling responsively down only though from its max-width or default width). I don't expect a user to understand the complexities/variations of responsiveness and I don't think they need to either, simply build it into the template.

I think you'll still run into problems with you're example of pixelation, for example 
I upload an image 20 x 20px, select responsive and now the image is stretched to go full width of the content area. We want to limit options that might lead to broken sites.
And then if it didn't allow it to grow bigger than its original size with your option you can't combine it with a left/right/center alignment.

Maybe there are improvements that can be made to the default templates and examples? I struggle to see how this is a user option when it should just be there already for them. If anything there might be the option for the user to say don't allow responsiveness on this particular image, but I don't think thats a core cms option.

**Comment by mfendeksilverstripe** [comment]
If I understand correctly, you're saying that having responsive images inside HTML which is managed by the CMS user via WYSIWYG is not recommended and therefore we don't want to support it out of the box. Is that correct?

What about iframes? Embedding video have similar issues as the interface doesn't allow responsive layout. Static dimensions are forced instead. Should we recommend to the client to avoid having these option user managed in the WYSIWYG?

**Comment by clarkepaul** [comment]
I'm saying responsive images are supported and should be the default but applied by the development team if their site has been built responsively. If this has been done by developers it doesn't make sense to also have this as a user option. Responsive images can be used in conjunction with all the alignment options we currently have, so if you were to make it a user option to opt into you'd want it to be separate from the alignment options.

Embedding video etc. Applying max-width 100% to all of those will stop them extending outside of the given space. Max-width naturally overrides width making them all responsive.

There might be some scenarios for content blocks which are edge case I'm not thinking about?

**Comment by mfendeksilverstripe** [comment]
Thanks for clarification, I guess that makes sense :) Closing this as no changes are needed here.
