### ISSUE TITLE
Folders appear on second page when sorting list view

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1108]
# Steps to reproduce
* Navigate to a folder with sub folders and 50+ files
* Switch to list view
* Notice that folders appear at the top of the list
* Sort the files by a different order

Expected results: Folders displayed first
Actual results: Folders are not displayed first. However if you navigate to the second page they appear at the top.

https://youtu.be/GY-fLxTCGBM

# Notes 
The grid view works as expected and if you have less than 50 entries the folder appear as expected in the list view

### PRs
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1222

**Comment by emteknetnz** [comment]
I had 2 folders where I changed their names after uploading several dozen files, this meant the folders LastEdited was greater than all the filters

Use the query `/admin/assets/?view=table&sort=lastEdited%2Casc&page=2`
- sort by LastEdited ASC
- page 2

The graphql query on page 2 returned 20 child nodes for the files, of which 19 and 20 were the folders

So it seems the issue is that the graphql query is not returning the folders 'in front' of all the regular files, instead it's treating folders like files, and then presumably react is what's putting the folders at the top of the results

**Comment by emteknetnz** [comment]
Possibly we could do this in the graphql query, though it seems as though we cannot specify multiple sortBy's + multiple directions?

https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/state/files/readFilesQuery.js#L44
```js
        sortBy: (sortField && sortDir)
          ? [{ field: sortField, direction: sortDir.toUpperCase() }]
          : undefined,
      },
```

https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/state/files/readFilesQuery.js#L93
```js
const query = {
  apolloConfig,
  templateName: READ,
  pluralName: 'Files',
  pagination: false,
  params: {
    limit: 'Int!',
    offset: 'Int!',
    rootFilter: 'FileFilterInput',
    childrenFilter: 'FileFilterInput',
    sortBy: '[ChildrenSortInputType]',
  },
```

**Comment by michalkleiner** [comment]
Mind that there could be other subclasses of File, not just Folder, so that could mess up things more if sorting _just_ by the class, _just_ alphabetically.

**Comment by emteknetnz** [comment]
Yeah I don't know how else we'd do this without using ClassName though, we're restricted by this 

`Does not support in-memory sorting for composite values (getters).`

https://github.com/silverstripe/silverstripe-graphql/blob/3/src/Pagination/Connection.php#L71
```php
    /**
     * @var array Keyed by field argument name, values as DataObject column names.
     * Does not support in-memory sorting for composite values (getters).
     */
    protected $sortableFields = [];
```

Totally makes sense, otherwise you'd need to fetch an entire database table, derive all the values for the getters and THEN return the 50 records you wanted.  That obviously wouldn't scale.  Currently what happens is the database will do a LIMIT 50 OFFSET 50 type of thing for pagination

It's a shame because there is a `type` derived field returned in graphql which is 'File' or 'Folder'.  If we could use that it would support File sub-classes

Given this functionality is already broken, and that subclasses of File are probably fairly uncommon, I'd say that sorting by ClassName DESC is still going to be a net improvement here

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/1130

**Comment by maxime-rainville** [comment]
This seems to somewhat resolve it for me https://github.com/silverstripe/silverstripe-asset-admin/pull/1134

I'm still trying to decide if my approach is pure brilliance and plain stupid.

**Comment by michalkleiner** [comment]
Nice one @maxime-rainville. I think it could work, it's something I'd say @unclecheese would do.

**Comment by maxime-rainville** [comment]
Done
