### ISSUE TITLE
Upload button broken after moving files

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1120]
If you move files to a different folder and navigate to that folder, the upload button doesn't work any more. Interestingly, the drag and drop for your file manager works just fine.

# Step to reproduce
- Access a folder with some pre-existing file and some pre-existing test folder
- Select the files
- Move the file to the test folder by dragging your selection over the folder.
- Navigate to the test folder
- Click the "Upload" button

Expected results: A file dialog allow pop up and allows you to select files to upload
Actual results: Nothing happens. This JS error is displayed: 
```
Uncaught TypeError: Cannot read property 'click' of null
    at HTMLButtonElement.click (bundle.js?m=1595570320:1)
click @ bundle.js?m=1595570320:1
```

[Youtube recording of the bug](https://youtu.be/YDdOcYEu138)

Reproduced in Chrome and Firefox. Didn't test in other browsers.

**Comment by tom890180** [comment]
Firefox spews a variable:

```
Uncaught TypeError: e.hiddenFileInput is null
    click http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    addEventListener http://localhost/(project)/resources/vendor/silverstripe/admin/client/dist/js/vendor.js?m=1581903006:1
    value http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    value http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    value http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    value http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    value http://localhost/(project)/resources/vendor/silverstripe/asset-admin/client/dist/js/bundle.js?m=1600147545:1
    pn http://localhost/(project)/resources/vendor/silverstripe/admin/client/dist/js/vendor.js?m=1581903006:1
    Dn http://localhost/(project)/resources/vendor/silverstripe/admin/client/dist/js/vendor.js?m=1581903006:1
...
```

It seems to be failing on this line:
https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/containers/Editor/Editor.js#L161

Probably because https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/containers/Editor/Editor.js#L157 returns null. 

.dz-input-PreviewImage is an element that only exists when an image is being previewed.

So, if you were to open the preview of an image prior to clicking on "Upload", it'll work, Curiously it'll work as well if you preview an image, then close the preview, and then click upload. 

replaceFile() in Editor.js is being called here, this is probably wrong because no file should be being replaced here .. it's called from here:
https://github.com/silverstripe/silverstripe-asset-admin/blob/a35d1a3cb7b02d488eff3f36613de0ef004478a0/client/src/containers/Editor/Editor.js#L76

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/1165
