### ISSUE TITLE
Vertical scrolling missing from asset details

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-asset-admin#1163]
On Chrome 87/Edge 88 the asset details panel is missing the vertical scroll bar:

![image](https://user-images.githubusercontent.com/6816/99604001-61762f00-2a69-11eb-9cf2-4341f0ea58a6.png)

Using the scroll wheel etc doesn't allow the panel to be scrolled either.

**Comment by lerni** [comment]
one way fixing this is setting `fieldset` to `max-height: 100%;`

![Bildschirmfoto 2020-12-01 um 18 17 46](https://user-images.githubusercontent.com/472115/100774998-f7fc0600-3402-11eb-94b7-d2a2cc4046f9.png)

...unfortunately yarn doesntt behave, to bring this any further :(
`Error: ENOENT: no such file or directory, chmod '...vendor/silverstripe/asset-admin/node_modules/@silverstripe/webpack-config/node_modules/.bin/webpack'`

**Comment by emteknetnz** [comment]
Replicated issue on 4.7.0-rc1 using chrome on ubuntu

It seems like it's only chrome 87 (and any other chromium based browser) that has this issue
 
Using browser stack with different versions of chrome for windows

silverstripe/recipe-cms 4.6.2

88 beta - not broken
87 - broken
86 - not broken
85 - not broken

silverstripe/recipe-cms 4.5.2

88 beta - not broken
87 - broken
86 - not broken

**Comment by emteknetnz** [comment]
We've spent a fair bit of time investigating this issue and we've deemed it an issue with chrome, rather than an issue with silverstripe

We were able to replicate this issue on chrome 87.0.4280.66, however not on 87.0.4280.88

I'm going to mark this issue as closed since we won't be fixing it ourselves and we'll instead we'll rely on automatic browser updates.

If it's critically important that you fix this yourself on one of your projects, this [closed PR](https://github.com/silverstripe/silverstripe-asset-admin/pull/1170) has one-liner of CSS that can be added that seems like it fixes the issue
