### ISSUE TITLE
Broken build - Change sort order behat - graphql 4 only

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#1186]
GraphQL 4 only

https://travis-ci.com/github/silverstripe/silverstripe-asset-admin/jobs/499392194

tests/behat/features/change-sort-order.feature:12

**Comment by unclecheese** [comment]
Source of the issue, and the [related campaign-admin issue](https://github.com/silverstripe/silverstripe-campaign-admin/issues/192) is that the graphql build side effect that generates the `admin.types.graphql` is failing because `silverstripe/event-dispatcher` is expecting `symfony/event-dispatcher` to use an API that is only in `symfony/event-dispatcher: ^4.3`. (Symfony did a breaking change between 4.2 and 4.4.. deprecation warning in 4.3)

`behat/behat` is forcing `4.0.0` of `symfony/event-dispather`, which isn't high enough.

Upgrading `behat/behat` to 3.6 or higher, and using `silverstripe/event-dispatcher: 0.1.1` (YAML bug) resolves the issue.

There are several things that needed to be updated here to make it work. We likely need an update to the travis build, PRs to composer.json files of dependencies, or both.

I'm thinking:
* Update silverstripe/event-dispatcher to use ^4.3 (https://github.com/silverstripe/silverstripe-graphql/commit/d38230c6d45714ff2ec4fd848d2e99d924e443ca). Module is broken in < 4.3 anyway, so this is a bugfix.

* Tag new event-dispatcher 0.1.2

* Update graphql to 0.1.2 tag

Behat is on 3.4, which is locked to  `symfony/event-dispacher:~4.0`, which _should_ tolerate 4.4, since there's nothing in the third column.

Happy to get some feedback before I update the dependencies.

**Comment by emteknetnz** [comment]
Sounds like a good plan

Though what does `Update graphql to 0.1.2 tag` mean?

**Comment by unclecheese** [comment]
Sorry, that was unclear. Update graphql to use the 0.1.2 tag of event dispatcher.

**Comment by emteknetnz** [comment]
Doesn't seem like the [PR to update this](https://github.com/silverstripe/silverstripe-graphql/commit/baa89d138b317f3664d1c78a6fed071614124056) fixed this issue

https://travis-ci.com/github/silverstripe/silverstripe-asset-admin/jobs/505064951

composer show:
behat/behat v3.8.1
silverstripe/event-dispatcher 0.1.2
symfony/event-dispatcher v5.2.4
