### ISSUE TITLE
PHP test folder missing

### ISSUE THREAD

**Issue by mark-a-j-adriano** [silverstripe/silverstripe-asset-admin#1306]
Scenario 1:
- Add `asset-admin` via composer install
- `tests/php` folder is missing on `vendor` folder

Scenario2:
- open [1.11.2 release](https://github.com/silverstripe/silverstripe-asset-admin/releases/tag/1.11.2)
- download the attached Zip or tar.gz file
- - `tests/php` folder is missing

**Comment by lozcalver** [comment]
This is intentional, tests are excluded across all core repos to keep download/install sizes down: https://github.com/silverstripe/silverstripe-asset-admin/blob/14233ba4b355ae2e19d5a45b47d41da73ad7996f/.gitattributes#L1-L3

You can use the `--prefer-source` flag when installing with composer to keep these directories
