### ISSUE TITLE
BUG Creating folder doesn't refresh UI

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#209]
After creating a folder the json response for the new folder is returned, but the UI won't display this until a refresh.

`{"ParentID":0,"ID":3,"Filename":"Uploads\/"}` for instance.

I would expect "Uploads" to appear beside the folder here.

![image](https://cloud.githubusercontent.com/assets/936064/17279777/8e3183b0-57d1-11e6-80b3-c4f8588a074c.png)

**Comment by sminnee** [comment]
The former behaviour was to open the new folder. I believe that this bug was introduced by the routing refactor and may relate to https://github.com/silverstripe/silverstripe-framework/issues/5797

**Comment by chillu** [comment]
Fixed through https://github.com/silverstripe/silverstripe-asset-admin/pull/231.

**Comment by flamerohr** [comment]
Peer reviewed
Looks good with minor comments added, perhaps fix/mark the few code climate issues?

New behaviour: it no longer redirects to the folder created, it refreshes the screen to display the new folder in the current screen.

Ingo and I had discussed on Friday about chaining the promise with a redirect instead of refresh, which gives the older user experience back but potentially presents new issues and not follow redux practices of predictable outcomes.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/231
