### ISSUE TITLE
API Enable react UploadField.js support within non-react sections

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#297]
In order to fully deprecate framework UploadField it will be necessary to build an uploadfield which works outside of react.

I propose creating a react wrapper around https://github.com/silverstripe/silverstripe-asset-admin/issues/296 which will bootstrap react / redux around UploadField.js, allowing it to be used in place of any uploadfield.

Acceptance Criterea:
 - The asset-admin UploadField can be used in php forms
 - This UploadField allows files to be added or removed from a has_one or many_many
 - Look and feel matches designs
 
Tasks:
 - [x] Fix js errors https://github.com/silverstripe/silverstripe-asset-admin/pull/329
 - [x] Merge framework PR https://github.com/silverstripe/silverstripe-framework/pull/6392
 - [ ] Merge asset-admin PR https://github.com/silverstripe/silverstripe-asset-admin/pull/331
 - [x] Get UploadField.js to render in a normal form
 - [x] Form submission works
 - [x] Upgrading notes / guide

**Comment by chillu** [comment]
Once that's implemented we'll want to remove the original `UploadField`, since we'll have a mostly equivalent replacement. Sam, Damian and myself have decided that the new 4.x `AssetField` should be removed altogether without a replacement, since its use case isn't well defined yet (saving `DBField` straight onto a record). `AssetField` relies on `UploadField` JavaScript and CSS, and we're aiming to get rid of that complexity from core.

**Comment by tractorcow** [comment]
By removed, we mean deprecated for now right?

**Comment by chillu** [comment]
I would've thought removed (or maybe moved to a module), assuming we can provide 95% equivalent features in the new `FileField`. And there's no reason to deprecate `AssetField` because it's not even in a stable release yet.

**Comment by chillu** [comment]
Turns out the old field hasn't been removed as part of this work, here's a follow up ticket: https://github.com/silverstripe/silverstripe-framework/issues/6481
