### ISSUE TITLE
Increase pagination from 15 to 50, after performance is improved

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#358]
Due to performance issues described in https://github.com/silverstripe/silverstripe-framework/issues/6457, @chillu had reduced the items per page from 50 to 15.

The choice of 50 was deliberate as it improves the usability of a paginated interface. For example, with 15 per page the chance of the first page being mostly folders, and confusing users, is quite high.

Once we've solved the performance issues we should re-increase the items per page to 50.

**Comment by tractorcow** [comment]
ok, so I was thinking about thumbnails / image optimisation

I think we need an API that allows us to get existing manipulations (e.g. padded, resized) which ONLY get existing generated images E.g. `$Image.Pad(100, 100)` gets a padded image, and if not regenerates it

We probably need `$Image.Existing.Pad(100, 100)` which only gets the padded version if found (edited). This is important, because when we are retrieving a list of 30 images per request, we cannot risk loading 30 images into memory and lazy-generating thumbnails. Of those 30 images, a set number of those images may not have thumbnails, and we have some other process of re-generating those thumbnails (outside of the initial pagination query) e.g. just some other endpoint

Secondly, for the request to 50 images, we should (for thumbnails that exist) ensure that protected image thumbnails are sent via base64 encoded blobs in the parent request, to avoid unnecessary requests to the protectedfilecontroller

**Comment by tractorcow** [comment]
@sminnee @chillu for your comment above, before I jump into implementation. :)

**Comment by tractorcow** [comment]
Rough pseudocode for my ExistingOnly method.

```php
public function ExistingOnly() {
    $dbfile = DBFile::create();
    $dbfile->Filename = $this->Filename;
    $dbFile->Hash = $this->Hash;
    $dbFile->Variant = $this->Variant
    $dbFile->canGenerate = false;
    return $dbFile;
}
```

With a check in ImageManipulation::manipulate() on the canGenerate property.

**Comment by clarkepaul** [comment]
An observation more than an issue is that pagination only kicks in after the files area is reloaded. You can upload 1000 files and they will show all on one page, if you navigate away and back again they are limited on each page through pagination.

**Comment by chillu** [comment]
Closing this in favour of https://github.com/silverstripe/silverstripe-framework/issues/6457 to avoid fragmenting the discussion (moved comments over there)
