### ISSUE TITLE
Assets can not be resolved on SSP (symlinked assets folder)

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#362]
In a site hosted on SSP, none of the assets will load.

Uploading a new image shows the preview, then when you navigate away and back again it is gone.

The network browser tells me that the thumbnails it tries to load are just my root domain, no filename included. I don't see `assets/` as a prefix to the filenames that are returned in the GraphQL, just for example `Uploads/filename.jpg`

---

I can replicate this locally by changing my assets directory to a symlink. Note: the underlying league/flysystem package [does not support symlinks](https://github.com/thephpleague/flysystem/issues/599).

**Comment by robbieaverill** [comment]
cc @marcello-silverstripe

**Comment by tractorcow** [comment]
Answer is in https://github.com/thephpleague/flysystem/issues/599#issuecomment-185221354; We just need a `realpath` in `AssetAdapter::findRoot` to ensure we work with the symlinked path as the root, rather than the symlink alias.

**Comment by tractorcow** [comment]
ok, after much debugging, we found the bug is in PublicAssetAdapter::getPublicURL()

It uses realpath($this->getPathPrefix), which may not be whithin BASE_PATH once resolved from a symlink.

The fix is to store a logicalPathPrefix when we construct the adapter, and compare this to base_path (without realpath).

Also, instead of falling back to returning null, we can assume $dir === ASSET_DIR instead. :D

**Comment by tractorcow** [comment]
Updated fix at https://github.com/silverstripe/silverstripe-framework/pull/6565
