### ISSUE TITLE
Minor spacing issues of thumbnails and back arrow

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#422]
Files require 20px gap left of the thumbnail in this case and the up folder action should only be 10px from the left (both files list view and insert media list view).

<img width="117" alt="pasted_image_6_04_17__10_49_pm" src="https://cloud.githubusercontent.com/assets/555033/24750929/d86bee6c-1b1b-11e7-9656-f688e48141f8.png">

**Comment by chillu** [comment]
Pointers how to fix: `TableView.js` in asset-admin has a `renderThumbnail()` method. Styling is done in `TableView.scss`

**Comment by phalkunz** [comment]
This is assigned to Mikaela Y

**Comment by phalkunz** [comment]
I think we shouldn't fix the folder action buttons group alignment in this issue. This isn't simple as it looks because the buttons have hover state which causes the buttons have different bounding boxes when in normal and hover states. @clarkepaul I think we talked about hover states earlier. There should be another issue to address this.

**Comment by mikaelayoung** [comment]
Merge Request: https://github.com/silverstripe/silverstripe-asset-admin/pull/436
