### ISSUE TITLE
Inconsistent thumbnail image scaling in asset admin gallery

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-asset-admin#434]
It was found while discussing https://github.com/silverstripe/silverstripe-admin/pull/31. We agreed that the thumbnail images should be zoomed out, not zoomed in/enlarged to fill the space, so that the whole images are displayed.

![b138b5e2-2448-11e7-85ec-2665c0d3358c](https://cloud.githubusercontent.com/assets/318116/25154448/d4667710-24e4-11e7-9925-feec82a658f6.png)

The last two images have the similar aspect ration as the second image but the thumbnail previews are different than that of the second image.

**Comment by chillu** [comment]
Pointer how to fix this: `FileTypeCreator.php` builds the GraphQL type, see `resolveThumbnailField()`

**Comment by phalkunz** [comment]
Assigned to Mikaela Y.

**Comment by mikaelayoung** [comment]
Merge request: https://github.com/silverstripe/silverstripe-asset-admin/pull/438

**Comment by clarkepaul** [comment]
I disagree with this decision, it makes a full page of assets very inconsistent to look at and very busy. Way beck we did a fair bit of research into how other asset libraries are laid out (ones which aren't purely photo based) and found that they also use a cropped view for consistency and ease of viewing as a whole rather than ease to recognise the shape.

**Comment by chillu** [comment]
@clarkepaul Fair enough, I've opened a PR to rever this: https://github.com/silverstripe/silverstripe-asset-admin/pull/469
