### ISSUE TITLE
Large folder breaks GraphQL fetch

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#536]
I created a folder with 185 images in it by dragging a large folder from my desktop into the browser. (Surprisingly) this worked pretty well!

However when I reloaded the folder, the GraphQL query timed out, putting an HTML "timeout error" message in the response showing "Folder cannot be found" on the client.

The resampled images are all present on disk (I think this happened during upload) so it's not a resample-time issue.

It seems like there are two potential problems:

 * Limit isn't being respected
 * GraphQL needs substantial optimisation

## Related

 * [Upload can't handle large amount of files](https://github.com/silverstripe/silverstripe-asset-admin/issues/139)
 * [Optimise Gallery Transfer](https://github.com/silverstripe/silverstripe-framework/issues/6457)
 * [Pregenerate thumbs on upload](https://github.com/silverstripe/silverstripe-asset-admin/issues/462)
 * [Uploading larger files breaks the error message](https://github.com/silverstripe/silverstripe-asset-admin/issues/532)
 * [Misleading error message when API loading fails](https://github.com/silverstripe/silverstripe-asset-admin/issues/528)

----

# PRs

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/697
- [x] https://github.com/silverstripe/silverstripe-assets/pull/100
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7618
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/101

**Comment by chillu** [comment]
I don't think either of the "potential problems" raised is the root cause here. The crux is that inlined thumbnail generation of protected files (so all files after upload) is slow to start with. That'll be adressed in [Optimise Gallery Thumbnail Transfer](https://github.com/silverstripe/silverstripe-framework/issues/6457). And to make matters worse, we seem to destruct and reconstruct thumbnails a few times in the same process, see https://github.com/silverstripe/silverstripe-assets/pull/44

**Comment by sminnee** [comment]
Yeah — that's encouraging as a GraphQL-wide problem would be harder to fix. ;)

**Comment by chillu** [comment]
@tractorcow Can you please doublecheck and estimate?

**Comment by tractorcow** [comment]
The issue was initially caused by:
 - canView check on every item (slow)
 - thumbnail generation by graphql
 
 We changed the above to use batched permission checking, and thumbnails no longer generate via graphql.
 
 I'll re-test to ensure this is no longer an issue, but my earlier similar test (1000 folders, 10,000 files) showed the section to be usable after these fixes.

**Comment by flamerohr** [comment]
I've done some load testing:
I have been getting the following error when batch moving a list of files which have large filesizes: `__Fatal error__: Allowed memory size of 524288000 bytes exhausted (tried to allocate 24576 bytes) in `
it's not a consistent error, and hasn't happened since I flushed a second time... so maybe it was building a cache to generate this error?

I have been testing with large pagination sizes per page as well (200 per page) and haven't run into the memory issue, the contents of each page consisted of large image files and other file types.

**Comment by tractorcow** [comment]
When caching images, the backend only caches on variant / hash, which shouldn't be changed due to a simple rename.

I'll try to find out what cache is being "busted" by this rename.

**Comment by tractorcow** [comment]
It looks like this is failing due to intervention image being created for every image just to get the dimensions.

Although we added caching to image dimensions, we still end up having to load all images in the backend at least once, even if we aren't resizing the thumbnails.

**Comment by sminnee** [comment]
Can we warm that cache on upload, like we do with the image resize?

**Comment by tractorcow** [comment]
Found an easier fix.

Turn off force_resample by default.

**Comment by tractorcow** [comment]
> Can we warm that cache on upload and rename, like we do with the image resize?

We do that, but the cache doesn't exist forever, and once it expires it'll run into this issue again.

Turning off force_resample only fixes half the issue. we still query width / height in graphql and this could conditionally hit a completely cold cache.

**Comment by tractorcow** [comment]
I have improved performance with the following changes:

 - force_resample off by default; Prevents `__Resampled.jpg` being regenerated on gallery listing.
 - Remove `width` `height` from `fileFragment.js` query prevents these fields from being generated within graphql PHP handler (Note: Not removing from actual php interface; We simply avoid querying these for asset-admin).
 
 The final occurrence of images being bulk-loaded into memory by graphql is the thumbnail generator code.
 
 In the past we have modified thumbnail generation so that we avoided resampling during graphql paging, however we still query getWidth() / getHeight() on all images when querying for these thumbnails.
 
 For instance, this is the `ScaleWidth` code.
 
 ```ph

**Comment by chillu** [comment]
Great explanation, and a good tradeoff. The storage duplication is limited to files where the original fits exactly the dimensions requested, which will be fairly unusual. In 99% of cases, you'll need to resize once (not causing a duplicate, but rather a new resized file). And then use the cached version afterwards without incurring the memory impact of loading the original.

**Comment by tractorcow** [comment]
Ok I'll consider that an implicit acceptance of the general approach. :) I'll Create the PR tomorrow.

**Comment by tractorcow** [comment]
ok, implemented above. :)

**Comment by flamerohr** [comment]
This is a good trade off I think, I like the idea of shifting the checks to be done when they are actually needed - rather than anticipate the need, a kind of lazy-load/just-in-time.
It follows a similar principal to other performance improvements we've done earlier in the year :)

I did irk for a moment at the higher storage requirements but since I don't see storage being that expensive, it didn't last long...
