### ISSUE TITLE
Once you search an image you can't click on the file to edit (nor clear search)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#537]
Can't view search items.
Can't clear search results.
Tested on BETA1 demo
![image](https://user-images.githubusercontent.com/555033/27892287-ee5988fa-6252-11e7-9500-1dd82cb10bd5.png)

**Comment by phalkunz** [comment]
Just to add more details: The issue seems to occur consistently after clicking "Clear search" button. The error message is "Uncaught TypeError: Invalid attempt to destructure non-iterable instance." I traced back to `this.props.actions.reduxForm.initialize(...)` in `clearFormData` method in `Search.js` but I couldn't figure out why.

**Comment by flamerohr** [comment]
This may have been solved with the form injector clean up earlier last week, to confirm if this is still a bug.

**Comment by flamerohr** [comment]
Closing, as this issue is fixed when the form injector work got refactored.
