### ISSUE TITLE
Present docs linked in HTML with icons and size

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#676]
Currently, the files area can only apply two type of content onto the webpage, every other file types are displayed as links i.e. videos, audio, docs etc. This understandable as images and text are the most widely used, and video are streamed.

Doc files (especially PDFs) are also widely used. It would be good to improve the usability and appearance when a link is inserted into the CMS, by:

- Adding the "doc" icon on the left of the link, so users can quickly know the media type, without them looking for the extension.
- Showing size of the doc, so users can decide if they wish to download it.

**Related:**
#580
#563

**Comment by chillu** [comment]
The doc icons mean that you need to worry about the presentation of those in your template. I think we already add a CSS class so that websites can opt in to that behaviour (via CSS `:before` rules). I don't think we should make this mandatory. 

Regarding the doc size, is this still considered best practice with fast internet speeds? We'd need a way for authors to choose if this is displayed, since it can be disruptive in terms of text reading flow. 

@clarkepaul How high do you think the impact of this is? I'm not keen to accumulate low impact enhancements in this tracker. Maybe something for uservoice instead?

**Comment by clarkepaul** [comment]
There is a difference between wanting to add a doc as a link within the body of some text to placing a doc on a page, that's why I would think it would be useful to let the admin decide what sort of presentation the inserted doc should have. @chillu Your right that if there are classes with the link, a lot can be achieved by a dev in the template but it's hard to distinguish the editor's intentions whether they are placed within a body of text or individually.
Perhaps this is soon to be irrelevant as a TinyMCE issue as content blocks should cater to the placement of files within a list or singularly (not in a body of text) so perhaps this issue is more relevant in elemental as part of the a file block enhancement rather than an asset-admin issue.

**Comment by chillu** [comment]
Yeah exactly, I'd see this solved through a "document list" block. Closing issue, I don't see as fixing this beyond what's already there (CSS classes) anytime soon.
