### ISSUE TITLE
Allow defining max size in pixels for UploadField

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-asset-admin#691]
It would be great to add a setting to set the maximum size in pixels for images. Large images often fail to be converted to thumbnails due to php memory limit, which gives a very "buggy" feeling to the end user when no thumbnail is displayed.

Therefore I think it would be great to implement this
https://github.com/enyo/dropzone/wiki/FAQ#reject-images-based-on-image-dimensions

Actually, I even thinks it make sense to apply this as a default (based on php max memory, it should possible to compute a reasonable default). For high res images, maybe it would make sense to have a special class (like LargeImage) where a simple icon is displayed instead of attempting to generate a thumbnail and where resize features are disabled?

**Comment by chillu** [comment]
It would have to be opt-out in case you add a more sophisticated image backend (e.g. with queue/worker based image resize that can handle larger files). And as you suggest, there's a use case for uploading larger images without the need to resize them (e.g. an architect's website allowing download of high res plan images, from direct `<a>` links rather than `<img>` embeds). 

Maybe we just need more graceful handling in the UI to ensure the user knows the image has uploaded correctly?

**Comment by lekoala** [comment]
just ran into this issue again today (uploading an image right from unsplash.com, which is something I guess most end users would do), and the error is pretty ugly (it creates a file entry, but throw some kind of json error etc).
It would be really nice if there was some kind of validation before trying to use large images in upload field. The preview system would cause the whole page to crash if the image is too large, a problem that may only appear after a while and not in initial testing.
