### ISSUE TITLE
Bug: error occurs when checking a newly-uploaded file and publishing via "bulk actions"

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-asset-admin#699]
## Overview

A JavaScript error "File selected for publishing cannot be found: <ID>" occurs in `asset-admin` when attempting to publish a newly-uploaded file via the "bulk actions" toolbar at the top of the panel. Refreshing the entire admin allows the files to be published in this manner.

## Expected Behaviour

Checking one or more newly-uploaded files via their checkboxes and then clicking "... > Publish" via the bulk actions toolbar should publish each selected file.

## Observed Behaviour

The SS loading spinner appears but never vanishes, and the admin appears to be frozen. The browser console shows the following error (asset ID will vary):

![image](https://user-images.githubusercontent.com/1853705/33353732-58fcbf7e-d503-11e7-9e4f-31665021d860.png)

## Steps to Reproduce

1. Within `asset-admin`, upload a file from your computer.
2. Without refreshing the admin, check the new file's checkbox in the bottom-right.
3. Click the ellipsis (...) in the "bulk actions" toolbar that appears at the top of the panel.
4. Click "Publish".

For me on the platform below, this can be replicated 100% of the time.

## Platform

- Windows 10 Pro x64 1703 15063.726
- Firefox Developer Edition 58.0b6 x64
- SilverStripe 4.0.0

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/715

**Comment by tractorcow** [comment]
I've attempted to reproduce this on the current 4.0.x branch and it doesn't seem to be an issue.

Possibly this was fixed since 4.0.0 stable, or maybe it's windows-only.

@colintucker can you please check the HTTP respones for the admin/assets/api/createFile upload?

It should be JSON with the below format

![image](https://user-images.githubusercontent.com/936064/33403364-fa3acc66-d5c4-11e7-93d2-8918cb8be36d.png)

Possibly if files uploads are failing, subsequent attempts to publish could fail also.

**Comment by colintucker** [comment]
Sure, here's a test file I just uploaded:

![image](https://user-images.githubusercontent.com/1853705/33408377-4a691f4e-d5ca-11e7-997e-0e9cb697cd36.png)

**Comment by tractorcow** [comment]
We'll need to do a bit more work to attempt to reproduce it then. Thanks for the feedback so far!

**Comment by unclecheese** [comment]
The core issue here was that `ID` was not cast as an in the `createFile` API endpoint.

In fixing this, another issue came up. Deleting an existing file would cause uploaded files to disappear. To fix that, we'll remove the imperative call to `purgeUploadedFiles()` in `Gallery.js` https://github.com/silverstripe/silverstripe-asset-admin/blob/1.0/client/src/containers/Gallery/Gallery.js#L110

This was added long ago, when the assumption was that any mutation to the list would result in a wholesale refresh of the file list. Since then, we've added bulk delete/publish/unpublish, which uses apollo's `resultBehaviors` https://github.com/silverstripe/silverstripe-asset-admin/blob/1.0/client/src/state/files/deleteFilesMutation.js#L14, making the refresh less necessary. Because of that, purging the upload queue was over aggressive.
