### ISSUE TITLE
add UploadField.setDisplayFolderName() and UploadField.getDisplayFolderName()

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-asset-admin#742]
The methods UploadField.setDisplayFolderName() and UploadField.getDisplayFolderName() which were available in SS3 are missing in SS4. 

I would like to get this functionality back to open the file selection in a specific folder, rather than asset root. I am happy to create a pull request or a module, but I need some pointers to get this done. 

I believe the rootFilter for the graphql query for selecting files from the CMS is set in https://github.com/silverstripe/silverstripe-asset-admin/blob/1.0/client/src/state/files/readFilesQuery.js#L82. Is that correct? 
If so, how do I manipulate the folderId value?

I noticed that when I set a folder on an UploadField through UpladField.setFolderName(), the data-schema attribut contains parentid: "[ID of the folder]". Can we use that to open the file selection in that folder? If so, how?

Any help highly appreciated. Thanks.

**Comment by bummzack** [comment]
I actually like this proposal here better: https://github.com/silverstripe/silverstripe-admin/issues/438

Why? Because users might choose different folders to store their files in, or they want to use files from another folder. If you force them into a specific folder using `getDisplayFolderName`, then the user has to navigate out of that folder to get to their folder _every time_, which is basically just shifting the issue.

**Comment by xini** [comment]
@bummzack I love that idea. That definitely makes sense for a default UploadField, where no folder name is set. (Although it should be configurable to always open the selection at root level.)

The use case for my request is the following: For specific UploadFields I often set the folder where files should be stored in using setFolderName(). For example a staff profile would have an image and that image stores into /assets/staff/. 
If a folder name is explicitely set using setFolderName() I think it would make sense to offer that folder for file selection as well. This could be the default behaviour when a folder name is set, or it could be enabled using the config. 

Any thoughts?

**Comment by mediaclinic** [comment]
@xini This is just the exact case I'm having with SS4. If I can make user experience a bit better for end user to open right folder straight away combined with setFolderName, that's awesome. I have thought the structure of assets very well in SS3 with setFolderName. Now all that is gone in SS4. User have been able to go in different folder if needed. But very often that is not needed, if the structure is well planned.

**Comment by tractorcow** [comment]
Good idea, but if we are adding this feature we should probably go ahead and allow users to set a target folder as well. I.e. display upload folder destination, click to edit?

**Comment by xini** [comment]
@tractorcow you mean like https://github.com/silverstripe/silverstripe-selectupload? Sounds good to me!

**Comment by tractorcow** [comment]
Yeah but maybe just build it in.

Selectupload would need a complete rebuild for 4.0 compat, as a react injected component.

**Comment by xini** [comment]
Love it. I'd love to see all that in core!

**Comment by chillu** [comment]
> Good idea, but if we are adding this feature we should probably go ahead and allow users to set a target folder as well. I.e. display upload folder destination, click to edit?

Let's keep this simple so we have a chance of getting it done - provide the PHP API, ensure that a third party module like selectupload has enough extension points in core to work in SS4.

**Comment by chillu** [comment]
@sachajudd Jared said that you worked on this. Can you please talk to him and have a think about how we could communicate which folder files get uploaded in, so that authors can form a mental model of their file hierarchy.

**Comment by tractorcow** [comment]
So in 3.x the DisplayFolderName property was a string. It had no relation to the actual FolderName property.

I guess it could be a boolean, and if set to true this will show the `FolderName` property as a string. Otherwise, you can set it to an explicit string to override what is rendered. How does this feel?

**Comment by clarkepaul** [comment]
Is the setting of the predefined folder location done on each individual instance of the UploadField? 

Setting up a default folder sounds good to me but what happens if that folder is deleted? 

For a single file UploadField I only see this being helpful when it is initially empty, if you choose not to use an image from this folder but use a different location then I'd expect to be taken back to folder the file is in. Therefor to me the above above suggestions work when there is an empty single file UploadField or a multi-file UploadField (files can be added from different folders but as a suggestion there is a default location).

In the long run it probably makes sense for a user to be able to set the default folder themselves either through a checkbox (default to this folder), or re-selecting a new default location like the SelectUpload module.

**Comment by tractorcow** [comment]
Sorry, I've gone back and reinvestigated the DisplayFolderName property, and it's completely different to what I had understood sorry.

So FolderName property is the target name for new file uploads, but DisplayFolderName is the default folder name for `select from files`.

At the moment "add from files" starts the user in root.

![image](https://user-images.githubusercontent.com/936064/38227222-5b4005ba-3751-11e8-9cf7-c4628aa4d8a0.png)

Setting `$field->setDisplayFolderName('AnotherFolder')` would show that folder when adding existing files instead.

![image](https://user-images.githubusercontent.com/936064/38227272-92a7277c-3751-11e8-92ff-b256d67d4f2b.png)


The property name is really badly named to be honest. It's nothing to do with "Display" and is in fact "default folder".

**Comment by tractorcow** [comment]
This is what I thought DisplayFolderName was (which in reality is "fixed" on, and isn't an option).

![image](https://user-images.githubusercontent.com/936064/38227314-b3cfb1e4-3751-11e8-83ad-2aafe7cb0c0d.png)

**Comment by chillu** [comment]
Right, that still seems like a useful API, but probably under a better name. Doesn't look like it needs design work, right?

**Comment by tractorcow** [comment]
no let's skip it.

**Comment by xini** [comment]
Thanks for having a look into this, everyone. 

I believe setDisplayFolderName() is not actually needed as such. If a folder is set on an UploadField via setFolderName(), this should basically set the default folder for this UploadField. Which means that when the author wants to select a file that's already in the system, the file selection should open in that default folder. 

If a file in a different folder is attached, the file selection could open in the folder of that file, but it could also open in the default folder. I don't mind.

**Comment by tractorcow** [comment]
Yes we could solve this problem by just respecting FolderName too for this feature. It's a simple fact that the legacy behaviour had separate fields for each, but I don't see why we couldn't unify it in 4.x.

So what we are suggesting is that `setFolderName('SomeFolder')` would make sure that the "Add from files" dialog pre-selects that folder instead of opening at root.

**Comment by chillu** [comment]
I've separated out a card for viewing the upload target folder in the UI: https://github.com/silverstripe/silverstripe-asset-admin/issues/759. 

I agree that `setDisplayFolderName()` as a way to set the default folder for the "add from files" dialog, separately from `setFolderName()`, seems like overkill. Those two folders should be the same in 99% of use cases. They should be synced though when using `setFolderName()`, which I've captured via https://github.com/silverstripe/silverstripe-asset-admin/issues/760.

Closing this issue, since it's getting a bit too confusing - let's continue focused discussion on the two separate issues.
