### ISSUE TITLE
Respect UploadField->setFolderName() in "add from files" dialog

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#760]
# Overview

Partially reinstated the 3.x `setDisplayFolderName()` API, which allowed to set the dialog folder to a different one from the upload target folder (via `setFolderName()`).

# Acceptance Criteria

 * As a CMS author, I can consistently interact with folders in a given UploadField UI
 * When selecting files via "add from files", I start in the same folder as used for uploading new files

# Notes

 * Does not need to remember past selections beyond page loads.

# PRs
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/763

**Comment by tractorcow** [comment]
Looks good to me.

**Comment by maxime-rainville** [comment]
I've been cogitating about the best way to fix this. Here's the results of my thought process. Let me know if I'm on the right track.

# Couple thoughts about the interaction between the backend and frontend
* The backend needs to tell the frontend what the initial folder should be.
  * Looks like this is already done by passing a `parentid` in the upload filed `data-schema`.
  * The react component reads it and pass it along to AssetDropzone. It doesn't seem to be doing anything else with it however.
* The frontend needs a way to tell the backend where the uploaded file should be store has the user could change the folder.
  * It looks like AssetDropzone is already doing that as well. It appends a ParentID attribute to the POST request.
  * The UploadField just ignores the ParentID it receives back from the POST request however.

# Couple thoughts on back end implementation
* This shouldn't affect  FileField at all so the following class/interface/trait shouldn't be touched
  * SilverStripe\\Forms\\FileField
  * SilverStripe\\Forms\\FileHandleField
  * SilverStripe\\Forms\\UploadReceiver
* `UploadField::upload` needs to be updated to:
  * Read `ParentID` from `$request`.
  * Make sure it matches a valid folder.
  * Pass the FolderID or the FolderName (not sure which one is best right now) when it calls `FileUploadReceiver::saveTemporaryFile()`.
* `FileUploadReceiver::saveTemporaryFile()` needs to be updated to:
  * Accepts an optional FolderID/FolderName ... if we make it mandatory, it will break third party class that uses this trait.
  * When calling `$this->getUpload()->loadIntoFile()`, we need to pass the optional parameter if set, otherwise we default to providing the default FolderName.

# Uploading via Modal vs uploading on via UploadField

If you just drop a file on the form field, your file will be posted to the upload action on UploadField. (e.g.: `item/1/ItemEditForm/field/WhateverYourFieldNameIs/upload`).

If you click the _Add from files_ button, you can upload files to a specific folder via modal. This doesn't use UploadField at all. The POST request is sent to `/admin/assets/api/createFile` instead.

Sounds a bit weird having two endpoints for uploading files.

**Comment by maxime-rainville** [comment]
Almost got it working. Need to write some unit test.

A side effect of my solution is that the InsertMedaDialog now remembers what folder you were viewing after you close it. So if you reopen the dialog, it will start back where you left off. e.g.:
1. User opens the InsertMediaDialog.
1. User navigates to a different folder, but doesn't insert a file.
1. User close dialog.
1. User reopens dialog. Dialog will open to the folder navigated too in step 2.

Previously, the dialog would take you back to the assets root every time you open the dialog.

I'm calling this a feature. Feel free to disagree.
