### ISSUE TITLE
`UploadField` doesn't check if the current user can write files to folder

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#762]
# Steps to reproduce
1. Create a new folder and lock it down to Administrators.
1. Add an UploadField pointing to that folder in your `Page::getCMSFields()`.
1. Log in as an `Author` and start editing a page.
1. Drag a file into your UploadField.
1. The file will be created in the folder, even if the user doesn't have permissions to write to the folder.

The insert modal doesn't let you do it however.

Affected version 4.x-dev

# Expected behavior
The UploadField should block you from uploading a file and ideally provide some feedback to indicate the upload capability is not available.

**Comment by tractorcow** [comment]
Just to check my assumptions here, we are relying on user-code to call `canEdit` on a folder before setting `->setFolderName('somefolder')` as the internal uploadfield will not check it for us.

My question to core team is "should we rely on user-code checking, or should it be internally enforced"?

Typically these folders are hard-coded into the uploadfield getCMSFields, but could be soft-coded and include ACL check.

We have changed versioned permissions in the past to use a more permissive model (user code should check permissions, not enforced internally) due to issue with CLI / non-user scripts. I wonder what people think about this principal and how we should extend it to other ACL checks in the codebase.

**Comment by maxime-rainville** [comment]
To @tractorcow's point, I could imagine a scenario where the "bug" is the intended behavior. 

Let's say I want to limit the ability of some users to edit or interact with files in a specific folder, but I still want them to be able to upload files into the folder. If we enforce permission on the drop zone, then it wouldn't be possible to achieve that behavior.

That would be an argument for making it the developer's responsibility to enforce permission. Or for adding some sort of flag to explicitly tell the UploadField to not enforce permission.

**Comment by tractorcow** [comment]
Good enough I guess. ;) We can re-open this if we change our minds later.
