### ISSUE TITLE
State gets confused after moving, deleting, uploading files.

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#809]
Asset-admin has an annoying tendency to mix up its state when doing file operation. Which leads to ghost file entries.

Here's a couple examples:
* When deleting a newly added file, it's still visible https://www.youtube.com/watch?v=c8ZVXdeHKLY&feature=youtu.be
* When moving a file from one folder to a different one, it's not visible in the new folder. https://www.youtube.com/watch?v=_VEV7GCnVz8

# PR's

- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/843

**Comment by bergice** [comment]
Seems like this could be a race condition.

Adding `this.props.actions.files.readFiles();` with `setInterval(this.props.actions.files.readFiles, 10);` at `vendor/silverstripe/asset-admin/client/src/containers/AssetAdmin/AssetAdmin.js:645` seems to resolve the file not updating its location when moved between folders.

**Comment by bergice** [comment]
The problem is that we are not updating the cache manually after the move file/delete file mutations. We need to ensure the cache is always up to date.

This becomes tricky with the move file mutation as we can easily write the updated query to graphql, but with the pagination, sorting and search filters we would need to write every combination of these variables to the updated query. This is not a viable option and it does not look like Apollo GraphQL has a way for us to clear the cache for a specific query regardless of the variables provided.

The closest option would be to clear the store itself or just prevent the readFilesQuery from using the cache by setting the `options.fetchPolicy` to `network-only`.
