### ISSUE TITLE
Resizing an image width for inserting returns an error

### ISSUE THREAD

**Issue by dawb** [silverstripe/silverstripe-asset-admin#816]
When trying to insert an image via the wysiwyg and change it's dimensions we get returned the following error
-- Uncaught TypeError: Cannot read property 'value' of undefined - vendor.js?m=1528859553:1 -- 

![screen shot 2018-07-30 at 12 12 22 pm](https://user-images.githubusercontent.com/777930/43372158-eb7b94a8-93f1-11e8-958c-6f1d854573b8.png)

If you manually edit the values they also don't update when you insert the image and the sizing reverts back to the default values.

![screen shot 2018-07-30 at 12 12 13 pm](https://user-images.githubusercontent.com/777930/43372159-eba8b2a8-93f1-11e8-8802-75584c41506b.png)

# Related PR
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/818

**Comment by NightJar** [comment]
Thanks @dawb 

Could you please include some more information?
I assume by WYSIWYG you mean the Content field from a Page - but if this isn't the correct context then that can be impacting on how the system operates.

By manually edit I see you've included a screenshot of `asset-admin` - or is this the insert pop-up?

Could you please include a few easy steps to recreate?

**Comment by dawb** [comment]
@NightJar no worries, I've put the steps below. This same error appears to happen in both 4.2 and 4.1.2.

1. Within the content field for a page, click on the insert from files icon in the WYSIWYG bar.
2. This displays the insert pop-up screen.
3. Click on the image to be inserted from this screen.
4. Update the width value in the form in the right hand panel. (this will generate the javascript error posted above).
5. Click on the insert button.
6. Check the HTML output within the WYSIWYG vis the source code icon.
7. The width and height assigned in this will go back to the default and not to the new values added.

Let me know if you need anymore information to recreate it.

**Comment by maxime-rainville** [comment]
This may have been addressed by https://github.com/silverstripe/silverstripe-assets/issues/131. But it didn't make it to 4.2 however.

**Comment by dawb** [comment]
Thanks @maxime-rainville, the issue is marked as fixed but it doesn't appear to have made it to any of the releases as we've tested it in 4.1.2 and it's returning the same issue?

**Comment by NightJar** [comment]
Indeed Max has stated that it didn't make the 4.2 release, but...

Good news @dawb - you can be a test pilot! :D

You should be able to test @maxime-rainville's theory that this is fixed by updating your projects `composer.json` file. Should take about ~5 mins tops.
In the `"requirements"` section:
`"silverstripe/asset-admin": "dev-1 as 1.2.1"`
But be sure to change the alias (`as x.x.x`) to whatever number is appropriate as per the output of `composer show silverstripe/asset-admin` :)
https://github.com/silverstripe/recipe-cms/blob/4.2.1/composer.json#L11

then run `composer update` and you should pull in the patch.
`composer show | grep asset-admin` should show you the most recent commit hash, as per [the log](https://github.com/silverstripe/silverstripe-asset-admin/commits/1)

If this is fixed, then I think it is probably worthwhile backporting as a bugfix.
If it's not fixed, then this is still a valid issue :)

**Comment by NightJar** [comment]
I should hope it'd be back-portable, since it appears as a bugfix. Best to defer to @maxime-rainville and @lukereative about this though.

**Comment by NightJar** [comment]
It should get 'merged up' through the versions, yeh. They're all maintained as separate branches to allow for bugfixes (e.g. 1.2.2), and patches get merged between them (generally at release time).
