### ISSUE TITLE
When inserting images to content, alt text should autofill

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-asset-admin#840]
Currently when trying to insert files into CMS content using the `insert file` button the sidebar shows a few fields:

![image](https://user-images.githubusercontent.com/3260989/45661347-3faf5380-bb51-11e8-9817-ad67f0a80bcb.png)

This is the default state and "alt" text is blank, but the tooltip is filled with the file name. Alt text really shouldn't be empty (accessibility/html standards) - it should autofill with the same content as the title.

**Comment by clarkepaul** [comment]
I'm wondering if this was left blank because by using the file name you might end up with a worse experience (if it wasn't edited). You'd get a lot of "image 1" happening which passes accessibility but its a worse experience.

Making it a required field and leaving it empty might produce a better result for the end user?
I think a good middle ground would be to auto-fill the field but provide a better description that this needs to be readable (not image_1). Does this improve the Alt text description? "Readable text if the image can't be displayed. WCAG requirement"

**Comment by brynwhyman** [comment]
The following issues captures (re)implementing validation on the alt text field for CWP sites: https://github.com/silverstripe/cwp/issues/149

Noting here incase this ends up being implemented in this module instead.

**Comment by clarkepaul** [comment]
Related, has context for additional accessibility considerations https://github.com/silverstripe/silverstripe-framework/issues/9099

**Comment by brynwhyman** [comment]
Thank you for your report. We've bundled this work and will track it in the following issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/983
