### ISSUE TITLE
SVG support for files area

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#846]
This has been a much requested feature for a while now, I can't seem to see any other issue currently addressing this enhancement so picking up from Uservoice and surfacing here.

There is already some work done by @micschk here which might be of use https://github.com/restruct/silverstripe-svg-images

It can be done in a secure manor as per https://wordpress.org/plugins/safe-svg/ , not sure if that makes it 100% safe but worth looking into.

**Comment by phptek** [comment]
This gist, pairs down @micschk's work, to just the bare minimum to include an SVG as a preview in the CMS in the asset-admin and within an `UploadField`. It makes no effort to deal with resizing (Actually, there is logic in there that will do it, but it isn't called for reasons I am unwilling to investigate at this time).

**Comment by micschk** [comment]
>  It makes no effort to deal with resizing
SVG resizing is basically a matter of setting a width & height through CSS (no pixels to recalculate, as SVG is a line drawing). Hence no logic is really needed for this.

To actually resize and/or crop SVGs (without needing to use CSS), you could work with the viewbox (what stevie-mayhew/silverstripe-svg handles).

Note about SVG security: there really seems to be a *lot* of possible attack vectors with SVG/XML uploads. To properly sanitise them you'd really need some library with a decent community behind it, else things are bound to be overlooked. Eg I think as soon as you start to parse (in order to sanitise) you already expose yourself to server-side risks, and using regexes instead of parsing is probably going to cause all kinds of risks to be overlooked.

**Comment by phptek** [comment]
Understood. Context here is that SVG graphics in the project I'm working on, are only exposed via REST to a REACT client. I needed to do a lot of experimentation, even with the support of the available modules. So the gist simply supports the most minimal use-case possible, and leaves it for implementers to do their homework for.

**Comment by ChloeSartorelli** [comment]
We're simply not going to add official SVG support. There are too many security implications, real or perceived, and there are community modules available for the (frankly infrequent) need for it.
