### ISSUE TITLE
Change of setFolderName in Uploadfield needs to be publicised

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-asset-admin#872]
I had been using cms code like this:

```
    $imageField->setDisplayFolderName('Uploads/promotionalbanners');
```

The automatic display of "promotionalbanners" in the choose from cms selector was broken in 3.4. I posted about this in https://www.silverstripe.org/community/forums/general-questions/show/118551#post420370

I traced it to a function change that Chillu made https://github.com/silverstripe/silverstripe-framework/pull/2064

I never saw anything about this in Change notes and its actually quite significant!

**Comment by maxime-rainville** [comment]
`setFolderName` is briefly describe at https://docs.silverstripe.org/en/4/developer_guides/files/file_management/#uploadfield. If I understand the original issue correctly, the problem is that the behaviour of the method was changed in 3.4.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward. You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

Unless someone is inclined to argue that the behavior in 4 is inappropriate, I don't think this issue is still relevant. I'll close it for now. If you disagree, let us know in the comment and I'll reopen.
