### ISSUE TITLE
Max $insert_width is being ignored in 4.3

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-asset-admin#917]
Inserting a large image into the WYSIWYG editor usually defaults to inserting it at a max width of 600px or max height of 400px. But in 4.3 it seems to ignore these settings and inserts it at its original size instead, which is very annoying when dealing with large images, e.g. photos uploaded from a camera/phone, as you have to remember to manually set the width/height before inserting.

To reproduce:

1. In a SilverStripe 4.3 WYSIWYG, click **Insert Image**.
2. **Upload** a large image (or select on an existing one)

Before clicking "**Insert File**" note that the Width and Height are set to the image's full width and height, rather than the 600 or 400 px max:

![](http://spdr.me/Mv87rW+)

# Pulls request
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/1015

**Comment by purplespider** [comment]
Looks like this issue was caused by the renaming of the width and height fields in this commit: https://github.com/silverstripe/silverstripe-asset-admin/commit/333acfc5cbefbe15d5c91a4e920aaabc6f040009

**Comment by purplespider** [comment]
Any chance in this 4.3 regression getting fixed for 4.4? @maxime-rainville 

It affects any CMS user who adds a large image into the WYSIWYG field.

**Comment by maxime-rainville** [comment]
Sorry, we're already under crunch time. We won't have time to fix it in the 4.4 release.

**Comment by clarkepaul** [comment]
My preference would be to show a warning if an image was uploaded at a large size, and then another warning if a large image was used on a page (if a person was uploading directly from the page it only needs to be a single warning). How does that sound @purplespider ? I'll create a separate issue for this and link once created.

The 600px default width is actually annoying and a bad default which trips up content authors as to why an image is so small or pixelated.

**Comment by purplespider** [comment]
@clarkepaul I'm not sure if we're on the same page here. The most important part is that when a CMS user inserts an image into the WYSIWYG editor, no matter how large the original image is, it should not initially appear larger than the width of the WYSIWYG editor, as this makes it frustratingly tricky for the user to resize the image to their desired size, as the drag handles will be hidden, way off the side of the screen, and they will need to be dragged multiple times to get the image down to a sensible size. This is what is happening due to a 4.3 regression. See this video: http://spdr.me/z13sKu

SilverStripe has always had a default image width of 600px which meant that the above would be very unlikely to happen and all drag handles would be easily accessible to allow the user to easily make the image smaller or larger as they desired. See this video: http://spdr.me/bpvzu7

I'm sure you'll agree that the original experience is significantly better.

Most photos uploaded to a website are going to be well over 600px wide, so I can see warning messages being quite annoying as they'll appear nearly every time. And what would they say? I certainly wouldn't want them telling the user to resize the image before uploading, as in my experience many users wouldn't have a clue how to do this, and it isn't necessary when the website can automatically resize them. Equally, I know that most of the CMS users for my websites wouldn't have a clue what size to manually specify when either resizing an image or when manually entering a width before inserting. 

Can we look at resolving the regression to fix the annoying behaviour? Then look at improvements, such as perhaps allowing the default insert width to be set in config?

**Comment by clarkepaul** [comment]
Yup I did understand, you are focusing more on the using of an oversized image and I am more focused on the prevention of having super large files in the CMS in the first place so slightly different issues. 

I don't think the removal of the 600px default was intentional (well at least to my knowledge). From my experience authors used to just leave the image at the 600px default, even though the image was designed to be used at say 650px which makes the image blurry. And if they do resize the image they are at risk of enlarging it bigger than how it's uploaded. Personally, I think I'd prefer them knowing the original size so they only reduce the size rather enlarging it.

> Most photos uploaded to a website are going to be well over 600px wide, so I can see warning messages being quite annoying as they'll appear nearly every time. 

This notice would only appear at sizes say over 2000px (or whatever we recommend not going over) so it would only show with really unreasonable sizes. These warnings could also inform authors of page loading speeds too.

Agree that the resizing experience you showed is not good at all, there is the option to open the file placement details and edit the size although that takes you out of the editing context. In saying that someone must have gone through the selection and "Insert" step for it to get there. 

> most of the CMS users for my websites wouldn't have a clue what size to manually specify 

We usually specify the optimal size in the label of an area where the template isn't doing any auto-resizing (where we don't want all images to conform to a certain size). We have also linked to cropping/resizing online tools, most people are familiar with cropping nowadays (it's a shame we don't have it built in but we work with what we've got).

Just putting another idea out there, instead of the 600px default cant the image just be set to a max-width of the editor unless a specific dimension is entered? That's how most images are used in templates anyway and would be a truer reflection of how it would look in the website (max-width: 100%).

Otherwise, I think we should only resize by default if we tell them its been resized, and allow them to choose to use the original size. The author would have a hard time to resize the image to its original size (backwards experience of the first video you showed @purplespider). As you have said this could be an enhancement of the raised issue.

**Comment by purplespider** [comment]
> These warnings could also inform authors of page loading speeds too.

But I like how SilverStripe takes care of image resampling automatically to avoid issues with page loading speeds. So there is no need for users to worry about manually resizing large images before uploading. Removing this feature would be a severe backwards step IMHO.

> Just putting another idea out there, instead of the 600px default cant the image just be set to a max-width of the editor unless a specific dimension is entered? That's how most images are used in templates anyway and would be a truer reflection of how it would look in the website (max-width: 100%).

This did cross my mind, but this would break SilverStripe's automatic resampling, so despite the image only appearing at the width of the WYSIWYG field, SilverStripe would think it was set to its actual size, e.g. 4000px and so wouldn't resample it down to ~600px on the frontend, thus increasing page loading times.


I agree that there may be particular clients/sites where it would be better for images to always appear at actual size so they have more control when using pre-prepared images, but I strongly believe this should be an option rather than the default. It's a selling point of SilverStripe that I can tell my clients they can throw any sized image at it and it will automatically take care of resizing it for them so that page loading speeds aren't affected.

Something like the way Gmail handles images could be good, it automatically sets the size to "Best fit", but provides a single click option for "Original size":

![](http://spdr.me/wZKyEs+)

This would work well for both cases.

So can we agree that this unintended regression should first be resolved, then a separate enhancement could be looked at to allow users to easily set an inserted image to it's "original size". If you still feel the need to display warnings, these would really only be relevant if a user actively tries to display a huge image at its actual size, and not if SilverStripe is going to resample it for them anyway, as it should by default.

**Comment by clarkepaul** [comment]
Yup agree this regression could first be resolved. The warning will be an addition for those uploading images about the large size, and won't limit them. 

I'm still not sold on the 600px default as it doesn't seem like a very responsive solution and quality producing a result but apart from authors using smaller images and using them without restrictions I don't have a better solution.
Googles example is pretty much what I was trying to explain, we might have [Default size | Original file size], so I'll add another issue to describe this experience.

**Comment by clarkepaul** [comment]
Is the default of 600px configurable? say the majority of the site has a maximum 700px wide content area, can I change the default to that?

**Comment by purplespider** [comment]
Yes. `$insert_width` is initially [defined as 600 px here](https://github.com/silverstripe/silverstripe-asset-admin/blob/d320fa53216409ea70c0706af95a45e55ef28461/code/Controller/AssetAdminFile.php#L31). Along with a 400 px `insert_height`. So it is configurable with:

````
SilverStripe\AssetAdmin\Controller\AssetAdminFile:
  insert_width: 700
````
_(Obviously, this has no effect in 4.3+ due to the regression)_

600 px is a seemingly odd initial default, however, thinking about it, if it was much larger, then there would be no initial visual difference in the CMS between the various left/right wrap and center image alignment options. Ideally, I suppose, it would be possible to set a larger insert_width and height for the center alignment, than the left/right ones which would usually be smaller.

**Comment by maxime-rainville** [comment]
#1013 address the crux of the issue. Still need to write some unit tests. But that shouldn't be long.

**Comment by purplespider** [comment]
@maxime-rainville Thank you! That does indeed fix the reported regression.

**Comment by maxime-rainville** [comment]
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).
