### ISSUE TITLE
'Saved file' is displayed in History when removed everything from 'Title' and saved

### ISSUE THREAD

**Issue by kiran-redhat** [silverstripe/silverstripe-asset-admin#923]
![image](https://user-images.githubusercontent.com/17115939/54657377-15554780-4b2e-11e9-8644-c849333e3a11.png)

Steps to reproduce:
1. Upload and image and fill with something and save
2. Empty 'Title' and save the asset
Expecting to see something like 'Title been removed/emptied' however it says 'Saved file'

**Comment by robbieaverill** [comment]
@kiran-redhat thanks for raising this issue! Can you please provide the versions of SilverStripe you're using, as well as a clear description of your problem, steps to reproduce and expected behaviour?

**Comment by clarkepaul** [comment]
I think this might be quite an old version as we no longer have a history on files as a tab like that. I can't recall how much detail we provided in file history but I do remember we tried to explain the change (e.g. title changed). For out newer history we don't explain what the change is, just that its been saved/published with the intention we will introduce more activity detail in the future. Doesn't help much with this issue but you might find that if you update to a newer version you'll loose file history.

**Comment by chillu** [comment]
As above, can't reproduce this in 4.3 since there's no history tab. When we're re-introducing this tab, we're most likely doing it by incorporating https://github.com/silverstripe/silverstripe-versioned-snapshots. This changes the way any edits are presented, so we'll have to remember that "change to empty" is a use case. I'll note that on https://github.com/silverstripe/silverstripe-versioned/issues/68
