### ISSUE TITLE
Publish button has bad styles

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-asset-admin#940]
Viewing a file and hard refreshing the page while viewing file details causes strange behaviour in the publish button for that file.

![image](https://user-images.githubusercontent.com/778003/57266215-328aa900-70cf-11e9-9934-3f4c7602245c.png)

Hovering over it restores a "normal" look (same styles as the save button in the screenshot).

This is an accessibility issue.

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/942

**Comment by dnsl48** [comment]
This is 4.4.0-rc regression

**Comment by dnsl48** [comment]
This is caused by the bootstrap upgrade.

Outlined buttons implementation changed between 4.1 and 4.3.

bootstrap 4.1 [forces transparent background](https://github.com/twbs/bootstrap/blob/v4.1.3/scss/mixins/_buttons.scss#L59)

bootstrap 4.3 [does not do so](https://github.com/twbs/bootstrap/blob/v4.3.1/scss/mixins/_buttons.scss#L61)

**Comment by dnsl48** [comment]
The fix goes to 4.4.1
