### ISSUE TITLE
UX: "Used on" tab with "File Link" records is confusing to users and broken

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-asset-admin#943]
### Poor UX issue

![Screenshot 2019-05-15 12 05 13](https://user-images.githubusercontent.com/654636/57740001-d8f72f80-7709-11e9-9bc3-15d909994c03.png)

In the above screenshot, we see a table of the record's title (e.g.`getTitle()`)  and its content type (`singular_name()`). Because file link tracking is done through `many_many_through`, these `FileLink` objects come up as first class content types when they should be invisible to content editors.

An ideal fix would be one that detects these special linking dataobjects and instead presents the user with information about the dataobject that this file is on, rather than the ID of its linking object.

CC @newleeland @clarkepaul

### Broken functionality
Uploading a file, immediately shows it's being used throughout the CMS, when it's not. See Clakepaul's comment below

# Pull Requests
- [ ] ~https://github.com/silverstripe/silverstripe-assets/pull/328~
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/998

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-cms/issues/2428 cc @scott1702

**Comment by clarkepaul** [comment]
I think this issue is getting worse, I uploaded different images without using them on any page and this was the result. Does the amount of links relate to the size of the image and amount of thumbs produced?
![image](https://user-images.githubusercontent.com/555033/59727218-e6fc1b00-9288-11e9-9919-86629a036a21.png)
![image](https://user-images.githubusercontent.com/555033/59727249-04c98000-9289-11e9-9193-085c349401d1.png)

**Comment by chillu** [comment]
This also affects the Bambusa demo, and makes it harder for us to show the "campaigns" feature in a meaningful way
