### ISSUE TITLE
it takes a lot of clicks and it is hard to find "view" / "download" link.

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-asset-admin#947]
In  the asset admin, it is not very intuitive for me to find the file's download link (PDF).  Also, the icon shown on mouse-over for the download link is a _zoom in_ icon.  This is also confusing to me. I would recommend:

1. the edit pane shows the actual link that you can click on to open / download a file.

2. you can open / download the file directly from the tiles.

3. the zoom-in icon is replaced with the eye or a download icon. 

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1011

**Comment by maxime-rainville** [comment]
If you don't have CMS open in front of you https://youtu.be/cQESdH36H-Q

I think the Zoom-in icon is there because when you click on an image it will allow you to see the full-resolution version.

That doesn't make much sense when you don't have an actual thumbnail there or when the file can't actually be viewed in your browser.

**Comment by maxime-rainville** [comment]
@silverstripeux

**Comment by kinglozzer** [comment]
Agreed, it’s definitely too hard to find!

Semi-related issue (downloading files from `UploadField` directly): https://github.com/silverstripe/silverstripe-asset-admin/issues/822

**Comment by clarkepaul** [comment]
Yup agree these are half implementations of the design so not very well executed. The magnifying glass was supposed to open images in a modal and not it a new tab. It also depends on what you're trying to view and how your browser is configured as to whether something is downloaded. It was originally designed with a full URL link underneath the location (folder) field. A lot of these things happen because of an MVP state, but also things have also progressed since the original designs so it would need new designs done.

I think the magnifying action should still remain but could be improved by having it open in a modal for images, for other non-viewable files it could be a download icon instead.
A download icon might be better placed at the end of the URL (there was supposed to be a download link in the "more options" (...) dropdown but that also never happened as planned). 

Question: is having a download link in the "more options" dropdown enough of a step forward or does the location field require the full URL underneath it as per the original plans.

**Comment by sunnysideup** [comment]
Hi Paul,

I think we can perhaps simplify this by showing a full link to the file that people can click on. That will work for both downloads and non-downloads (images). That is simple to implement and i'd rather see that added than something more fancy never getting added.

**Comment by clarkepaul** [comment]
That's what the design was (a simple link showing full URL) attached to the location field. Would you be keen to implement it? It's just that with the current impact level it's not going to be a priority (same as why it didn't get implemented in the first place). If so we can supply guidance with design.

**Comment by newleeland** [comment]
It would be good to use a similar experience as UploadField dropdown options shown here:
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b5e6e3984472000117f3ee4

**Comment by maxime-rainville** [comment]
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).
