### ISSUE TITLE
ValidationResult::addError() doesn't show up anywhere in the UI

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#967]
**Version: 4.4.x-dev**

## Steps to reproduce

Add this to `Image`:

```php
    public function validate()
    {
        $validation = parent::validate();
        if ($this->isInDB() && empty($this->Title)) {
            $validation->addError('Testing error');
        }
        return $validation;
    }
```

Upload an image. This is successful (as expected) because the isInDB() check skips validation.

Open the image and remove the title, then try to save the image.

## Expected result

The image should not save. I should see "Testing error" somewhere in an error alert.

## Result

The image doesn't save (correct). No validation error is shown in the UI (bug).

---

This works with `$validation->addFieldError('Title', 'Testing error')`:

![image](https://user-images.githubusercontent.com/5170590/61280524-edaa7f00-a7af-11e9-8d48-46b9fb81200f.png)

## PRs
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1377 (for new files only - doesn't address editing existing files)
- https://github.com/silverstripe/silverstripe-admin/pull/1587

**Comment by blueo** [comment]
Just ran into something similar - seems to related to the changes here: https://github.com/silverstripe/silverstripe-asset-admin/pull/1138 . In my case the validation message isn't showing on an uploaded file thumbnail.

**Comment by blueo** [comment]
So it appears since 4.6 validation errors that are not attached to a field will not be displayed anywhere. As per the above description the Edit form will not display anything from addError but now we also don't get a validation message in the Thumbnail view:
eg with the following validation code on Image:

```PHP
$result->addError('The image already exists (' . $location . ')');
```

**before 4.6** the thumbnail displays the validation error:
![image](https://user-images.githubusercontent.com/948122/119747646-42a89780-bee7-11eb-93f5-e148540cb082.png)

**after 4.6** the thumbnail has a generic error:
![image](https://user-images.githubusercontent.com/948122/119747700-5fdd6600-bee7-11eb-8eb1-8f81ce59c32f.png)

I feel we need to find a home/better way of displaying these general errors in the admin

**Comment by blueo** [comment]
@emteknetnz FYI I think there is still an outstanding issue when 'addError' is called on an existing asset - so its only partially closed... @GuySartorelli has some context

**Comment by ChloeSartorelli** [comment]
Reopening this. As per the note in the issue description, this has only been resolved for _new_ files, but is still a problem for _existing_ files.

**Comment by ChloeSartorelli** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/1587.
This will be automatically tagged by GitHub Actions.
