### ISSUE TITLE
File replace does not show current version

### ISSUE THREAD

**Issue by amolswnz** [silverstripe/silverstripe-asset-admin#970]
### Steps to reproduce

- Upload a file in CMS
- Publish the file
- Select replace file
- Upload new file
- Save or Publish
- View the file 
- Error - The first uploaded version of the file is shown 
- Error - Last changed date time is not reflected

### Notes:
- Investigate how the thumbnails are being handled too. From the comments:
> If I replace the file and publish it right away, the main file gets published but the thumbnails don't get regenerated. If I first save the replace file and then publish it, the updated thumbnails get published along with the main file.

# Pulls request
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/984
* [x] https://github.com/silverstripe/silverstripe-assets/pull/325

**Comment by ScopeyNZ** [comment]
I've triaged but not validated this issue yet. I've dealt with this recently and it seemed to be working fine - perhaps there has been a regression. in 4.4.0.

**Comment by brynwhyman** [comment]
FWIW, I can't recreate this issue on `silverstripe/cms  4.1`

**Comment by maxime-rainville** [comment]
I think they're might be more than one bug at play here.

If I replace the file and publish it right away, the main file gets published but the thumbnails don't get regenerated. If I first save the replace file and then publish it, the updated thumbnails get published along with the main file.

On occasion, I have seen cases where the front end state doesn't get properly updated, but it's hard to replicate systematically.

**Comment by blueo** [comment]
I can confirm that saving before publishing will trigger the thumbnails to be re-generated but publishing before saving will leave outdated image variants.

there also seems to be a separate issue preventing the front-end from updating. If the name for the asset doesn't change, the preview url remains un-changed and so the field won't re-render and request the image download again. Adding a url param, such as last edited time seems to help with this problem

possibly linked to: https://github.com/silverstripe/silverstripe-asset-admin/issues/890

**Comment by blueo** [comment]
So I think I've tracked down part of this. Image variants rely on the `!$store->exists($filename, $hash, $variant)` check in the `ImageManipulation::manipulate` function. If the check fails to find an existing variant, it will try to re-generate the variant, if not, it skips. 

The problem arises when the asset store (`FlysystemAssetStore`) uses the `applyToFileOnFilesystem` to check if a variant exists. When pressing 'save' after uploading a replacement, this check returns 'false' as the uploaded file and exisiting file have different hashes (line 329). If, however, you press publish before pressing save then the check gets the same hash values and the store says the file exists. Because of this the variant generation is skipped.

https://github.com/silverstripe/silverstripe-assets/blob/fc17276f93c6a5110fbe91e0796d4f0051c1c482/src/Flysystem/FlysystemAssetStore.php#L312-L347

**Comment by maxime-rainville** [comment]
I've got a partial fix with https://github.com/silverstripe/silverstripe-asset-admin/pull/984.

This just adds a `vid` GET parameter when requesting thumbnails. This allows you to bust the browser cache when accessing re publish files.

That's not the main problem but it makes it easier to fix.

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-assets/pull/325 resolves the main problem.

**Comment by maxime-rainville** [comment]
There's nothing left to do with this.
